kitti_rec:
  ros__parameters:
    sequence: 0
    data_dir: '/mnt/f/datasets/KITTI/kitti-odom/data_odometry_color/dataset/'
    odom_dir: '/mnt/f/datasets/KITTI/kitti-odom/data_odometry_poses/'
    bag_dir : '/mnt/f/datasets/KITTI/kitti-odom/kitti-fixed/00'
    odom : True
